blogtitle: "The Soapbox"
blogdescription: "Desmond Rivet's Blog"
bloglang: "en"
blogurl: ""
page_size: 10
path_to_templates: /home/dcr/yawt_blog/templates
path_to_articles: /home/dcr/yawt_blog/content
path_to_static: static
ext: txt
meta_ext: md

# flavour to content_type
content_types: {
    "rss": "application/rss+xml"
}

plugins: {
    tagging: 'yawt.plugins.tagging',
    archiving: 'yawt.plugins.archiving',
    categories: 'yawt.plugins.categories',
    search: 'yawt.plugins.search',
    hgmeta: 'yawt.plugins.hgmeta',
    markdown_c: 'yawt.plugins.markdown_c'
}

archiving: {
    base: 'blog'
}

tagging: {
    base: 'blog'
}

categories: {
    base: 'blog'
}
