blogtitle: "Desmond's Soapbox"
blogdescription: "Musings from a Anglo-Quebecer"
bloglang: "en"
blogurl: "http://www.desmondrivet.net/blog"
page_size: 10
path_to_templates: templates
path_to_articles: entries
ext: txt
meta_ext: md

# flavour to content_type
content_types: {
    "rss": "application/rss+xml"
}

plugins: {
    tagging: 'yawt.plugins.tagging',
    archiving: 'yawt.plugins.archiving',
    search: 'yawt.plugins.search',
    hgmeta: 'yawt.plugins.hgmeta',
    markdown_c: 'yawt.plugins.markdown_c'
}
