YAWT_LANG: "en"
YAWT_BASE_URL: ""
YAWT_PAGE_SIZE: 10
YAWT_PATH_TO_TEMPLATES: templates
YAWT_PATH_TO_ARTICLES: content
YAWT_PATH_TO_STATIC: static
YAWT_STATIC_URL: /static
YAWT_EXT: txt
YAWT_META_EXT: meta

# flavour to content_type
YAWT_CONTENT_TYPES_RSS: "application/rss+xml"

YAWT_PLUGINS: {
    tagging: 'yawt.plugins.tagging',
    tagcounter: 'yawt.plugins.tagcounter',
    archiving: 'yawt.plugins.archiving',
    archivecounter: 'yawt.plugins.archivecounter',
    categories: 'yawt.plugins.categories',
    search: 'yawt.plugins.search',
}

archivecounter: {
    BASE: 'blog'
}

categories: {
    BASE: 'blog'
}

tagcounter: {
    BASE: 'blog'
}
