# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
        
    working_directory: ~/repo

    steps:       
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install pip requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: clone required git repos
          command: |
            . venv/bin/activate
            invoke clonedeps
            
      - run:
          name: build site
          command: |
            . venv/bin/activate
            invoke preview
            
      - persist_to_workspace:
          root: .
          paths:
            - output/
            - webmention_cache.yml
  deploy:
    docker:
      - image: circleci/node:9.9.0

    working_directory: ~/deploy
    
    steps:
      - attach_workspace:
          at: /tmp/workspace
          
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
            - node-deps-
            
      - run:
          name: install netlify-cli
          command: npm install netlify-cli
          
      - save_cache:
          paths:
            - ./node_modules
          key: node-deps-{{ checksum "package-lock.json" }}

      - run:
          name: deploy to netlify
          command: ./node_modules/.bin/netlify deploy --dir=/tmp/workspace/output --prod
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
